### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by wiggin77** [RealyUniqueName/JStack#10]
I'm reluctant to report this as I cannot give much to go on.   I have a mid-sized project now using JStack and when we compile we get:

```
$ haxe build.hxml 

/usr/lib/haxe/lib/jstack/2,3,4/format/js/haxe/CallStack.hx:15: characters 29-37 : You cannot access the js package while in a macro (for js.Error)
```
That is all the output from the compiler.

Using Haxe 3.4.2, compiling for JavaScript, and nodejs is defined.   We do have build macros which are likely causing this indirectly.  Unfortunately this error message provides little to go on in terms of which macro or what code is at fault.  

Is this something that can be addressed in `jstack/2,3,4/format/js/haxe/CallStack.hx`?

Thanks.

**Comment by RealyUniqueName** [comment]
Sorry for late answer. 
Could you please post a reproducible example?
Or change `js.Error` to `#if macro Dynamic #else js.Error #end` and tell me if that works. If it is, i will submit fixed version to haxelib.

**Comment by RealyUniqueName** [comment]
I managed to reproduce it by myself.
Fixed version is already on haxelib.

**Comment by wiggin77** [comment]
Thanks!
