### ISSUE TITLE
Haxe 4 compatibility

### ISSUE THREAD

**Issue by filt3rek** [RealyUniqueName/JStack#16]
Hej Aleksandr,

It seems not to work, I just see the errors in my page as before targeting to .php files.

I use latest Haxe 4 nightly build (but it does the same with preview 4), I compile to `-D php7` and I do `-D JSTACK_HAXE_DEV`

Is thee something I've missed please ?

Best,

**Comment by filt3rek** [comment]
Sorry, I forgot adding `-debug`
So now, I see nothing, a white page

**Comment by filt3rek** [comment]
I've tested again, digging why it doesn't work. So when I use JStack it doesn't write any log even in the apache log file. Without the lib, the errors are written in the log file.

**Comment by RealyUniqueName** [comment]
It works fine for me.
Can you provide a minimal sample, please?

**Comment by filt3rek** [comment]
Hej Aleksandr,
Thanks for your answer.
Well, maybe I do something wrong or I don't know how does it work, where to look at the output ?
`class Main {
	static function main() {
		throw "ok";
	}
}`
With that :
`haxe -php bin -main Main -D php7`
I can see the error thrown on the web page output
But with that :
 `haxe -php bin -main Main -D php7 -D JSTACK_HAXE_DEV -debug`
I see nothing in the web page output.

- Haxe Compiler 4.0.0-preview.4+bdccaccf3
- jstack git version 2.3.9

**Comment by filt3rek** [comment]
Hej Aleksander,

Have you seen why it doesn't work for me please ? Any advice or something ?

Regards,

**Comment by RealyUniqueName** [comment]
Sorry, I missed your response somehow. Will take a look tonight.

**Comment by filt3rek** [comment]
Thanks Aleksander ;)

**Comment by RealyUniqueName** [comment]
I didn't find why it could fail for you. 
There is always a possibility that you have a fancy setup, which does some magic with PHP's stderr or error handling.
JStack writes all uncaught exceptions to stderr.
Try this to find out if JStack at least handles your exceptions 
```haxe
var jstackHandler = jstack.JStack.uncaughtExceptionHandler;
jstack.JStack.uncaughtExceptionHandler = function(e) {
  var error = jstackHandler(e);
  trace(error);
  return error;
}
```

**Comment by filt3rek** [comment]
Aleksander,

Thanks for your answer.
In fact, with your explaination, It does work. I just didn't know it writes to stderr ! :)
Maybe I've missed that information or it's not clearly explained ?

Anyway, it work fine, thank you for your time and for this lib ;)

**Comment by RealyUniqueName** [comment]
By default, PHP writes unhandled exceptions to stderr, so I didn't even think that needs a mention )

**Comment by filt3rek** [comment]
When I used haxe/PHP 5, a throw was written to the web page so I thought it was the same here but instead nothing was displayed (empty page). But using your code (which traces to the web page) it does work, so that is what disturbed me.
