### ISSUE TITLE
JStack can crash the VSCode extension host

### ISSUE THREAD

**Issue by Gama11** [RealyUniqueName/JStack#17]
This piece of code seems to be bad news in VSCode, as it sometimes takes down the entire extension host:

https://github.com/RealyUniqueName/JStack/blob/d5014805f630cfc86c41a69243a46c4ad8f3cf3c/src/jstack/js/JStack.hx#L168-L170

![](https://i.imgur.com/hJUrJpz.png)

Curiously, VSCode sometimes manages to prevent it:

![](https://i.imgur.com/BWEmIJG.png)

Not sure if there's a way for JStack to detect it's running in VSCode, or is a define needed to turn this behavior off?

**Comment by RealyUniqueName** [comment]
`-D JSTACK_NO_SHUTDOWN` as of v2.3.11
