### ISSUE TITLE
JStack breaks main functions with return values

### ISSUE THREAD

**Issue by Gama11** [RealyUniqueName/JStack#9]
When we added an extension API to vshaxe, we had to disable JStack. The reason for this is that the API object has to be returned from `main()`, and JStack swallows the return value.

This is what the generated `main()` looks like without JStack:

```js
vshaxe.Main.main = $hx_exports["activate"] = function(context) {
	return new vshaxe.Main(context).api;
};
```

With JStack:

```js
vshaxe.Main.main = $hx_exports["activate"] = function(context) {
	jstack.js.JStack.onReady(function() {
		return new vshaxe.Main(context).api;
	});
};
```

As you can see, with JStack, the return value never makes it out of `main`.

**Comment by RealyUniqueName** [comment]
I can add "asynchronous" mode which will enable JStack once sourcemap is downloaded. But that means any error thrown synchronous with `main()` call will not be mapped.

**Comment by Gama11** [comment]
That would be some opt-in define I guess? Meaning it would still silently break things in case of return values. Would be good to have a warning so that doesn't happen.

**Comment by RealyUniqueName** [comment]
Warnings are things people tend to ignore :)
Maybe it's better to add a compiler error, which will ask to add a compiler flag, in case `return` in main function is spotted.

**Comment by Gama11** [comment]
That seems fine too.

**Comment by RealyUniqueName** [comment]
Pushed fixed version to haxelib. Try `-D JSTACK_ASYNC_ENTRY`

**Comment by Gama11** [comment]
Works great, thanks! 👍
